name: github pages

on:
  push:
    branches:
      - develop # default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages # settings -> environments -> need add 'develop' branch
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Install dependencies
        run: pnpm install

      - name: build packages
        run: pnpm build

      - name: Build with dumi
        run: cd website && pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 
        with:
          path: ./website/dist # 指定要部署的目录

      - name: Setup Pages
        uses: actions/configure-pages@v5 # 配置 GitHub Pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # 部署到 GitHub Pages
        id: deployment
        with:
          token: ${{ github.token }}
